#!/usr/bin/env python3

import os
import sys

from lib.cld import *
from ctx.ctx import *

DIR = os.path.dirname(os.path.realpath(sys.argv[0]))

if len(sys.argv) < 2:
    print("Usage: /path/to/do-translate /path/to/cld.config")
    sys.exit(1)

CFG = sys.argv[-1]

print(CFG)
