package org.opengamestudio

const val ARGUMENT_DBG = "--dbg"
const val ARGUMENT_FILE = "--file"
const val ARGUMENT_OUT = "--out"
const val DBG_LEN = 50
const val FIELD_DELIMITER = ": "
const val FILE_EXTENSION_JAVASCRIPT = "js"
const val FILE_EXTENSION_KOTLIN = "kt"
const val FILE_EXTENSION_SWIFT = "swift"
const val LANGUAGE_JAVASCRIPT = "JavaScript"
const val LANGUAGE_KOTLIN = "Kotlin"
const val LANGUAGE_SWIFT = "Swift"
const val POSTFIX_ENTITY = ":"
const val PREFIX_COMMENT = "# "
const val PREFIX_FIELD = "        "
const val PREFIX_FIELD_COMMENT = "        # "
const val PREFIX_JAVASCRIPT = "javascript: "
const val PREFIX_KOTLIN = "kotlin: "
const val PREFIX_KOTLIN_COMMENT = "// "
const val PREFIX_SWIFT = "swift: "
const val PREFIX_TYPE = "    type: "
const val SECTION_FIELDS = "    fields:"
const val TYPE_CONTEXT = "context"
