#!/bin/bash -e
SCRIPT_DIR=$(cd "$(dirname "$0")" ; pwd -P)

swiftc \
    -o $SCRIPT_DIR/do-test \
    $SCRIPT_DIR/CLDContext.swift \
    $SCRIPT_DIR/CLDController.swift \
    $SCRIPT_DIR/test.swift \
    $SCRIPT_DIR/main.swift
