#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)

kotlinc-native \
    $SDIR/CLDContext.kt \
    $SDIR/CLDController.kt \
    $SDIR/main.kt \
    $SDIR/registerOneliners.kt \
    $SDIR/test.kt \
    -o $SDIR/do-test

# Get rid of the weird `kexe` extension on *nix
# JetBrains: Seriously, dudes, you won't break that rule, drop it
mv $SDIR/do-test{.kexe,}
